version: '3.7'

services:

  currency-exchange:
    image: asohrab18/microservice-eureka-client-x:latest
    mem_limit: 700m
    ports:
      - "8001:8001"
    networks:
      - currency-network
    depends_on:
      - eureka-discovery-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-discovery-server:8761/eureka

  currency-conversion:
    image: asohrab18/microservice-eureka-client-y:latest
    mem_limit: 700m
    ports:
      - "8002:8002"
    networks:
      - currency-network
    depends_on:
      - eureka-discovery-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-discovery-server:8761/eureka

  eureka-discovery-server:
    image: asohrab18/spring-cloud-discovery-eureka-server:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network: