version: '3.7'

services:

  currency-conversion-service:
    image: asohrab18/currency-conversion-service-image:latest
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - eureka-discovery-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-discovery-server:8761/eureka

  currency-exchange-service:
    image: asohrab18/currency-exchange-service-image:latest
    mem_limit: 700m
    ports:
      - "8004:8004"
    networks:
      - currency-network
    depends_on:
      - eureka-discovery-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-discovery-server:8761/eureka
      
  microservice-eureka-client-x:
    image: asohrab18/microservice-eureka-client-x-image:latest
    mem_limit: 700m
    ports:
      - "8001:8001"
    networks:
      - currency-network
    depends_on:
      - eureka-discovery-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-discovery-server:8761/eureka

  microservice-eureka-client-y:
    image: asohrab18/microservice-eureka-client-y-image:latest
    mem_limit: 700m
    ports:
      - "8002:8002"
    networks:
      - currency-network
    depends_on:
      - eureka-discovery-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-discovery-server:8761/eureka

  api-gateway:
    image: asohrab18/api-gateway-image:latest
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - eureka-discovery-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-discovery-server:8761/eureka

  eureka-discovery-server:
    image: asohrab18/spring-cloud-discovery-eureka-server-image:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network:
