INSERT INTO EMPLOYEE(EMP_NAME,SALARY,DESIGNATION,CITY,COUNTRY)VALUES('ALI',10000,'SSE','MACCA','SAUDI ARAB');
INSERT INTO EMPLOYEE(EMP_NAME,SALARY,DESIGNATION,CITY,COUNTRY)VALUES('CELINA',20000,'SINGER','MUMBAI','INDIA');
INSERT INTO EMPLOYEE(EMP_NAME,SALARY,DESIGNATION,CITY,COUNTRY)VALUES('DINESH',30000,'ARTIST','HYDERABAD','INDIA');
INSERT INTO EMPLOYEE(EMP_NAME,SALARY,DESIGNATION,CITY,COUNTRY)VALUES('JOHN',40000,'ARCHITECT','LONDON','UK');